[package]
name = "ca-languages"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
blake3.workspace = true
ca-core.workspace = true
thiserror.workspace = true
tree-sitter.workspace = true
tree-sitter-c-sharp.workspace = true
tree-sitter-dart.workspace = true
tree-sitter-go.workspace = true
tree-sitter-java.workspace = true
tree-sitter-javascript.workspace = true
tree-sitter-rust.workspace = true
tree-sitter-typescript.workspace = true

[lints]
workspace = true
